version: "3.8"

services:
  app:
    build:
      context: ./booking-hotels-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    ports:
      - "8080:8080"

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - ENCRYPT_KEY=IMSYMMETRIC

  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_DB: booking_hotels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"