version: "3.8"

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=jdbc:postgresql
      - DB_PORT=postgres:5432
      - SCHEMA_NAME=booking_hotels
      - DB_USERNAME=postgres
      - DB_USER_PASSWORD=postgres

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_DB: booking_hotels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"