version: "3.8"

services:
  booking-hotels-service:
    build:
      context: ./booking-hotels-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - EUREKA_HOST=eureka-server
      - POSTGRES_HOST=postgres
    ports:
      - "8180:8180"

  user-service:
    build:
      context: ./user-service
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    ports:
      - "8073:8073"

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - ENCRYPT_KEY=IMSYMMETRIC

  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071

  gateway-server:
    build: ./gateway-server
    ports:
      - "8072:8072"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_DB: booking_hotels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  keycloak-postgres:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: keycloak-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass

volumes:
  postgres_data:
    driver: local