spring.application.name: booking.hotels
spring:
  datasource:
    url: ${DB_HOST:jdbc:postgresql}://${DB_PORT:localhost:5432}/${SCHEMA_NAME:booking_hotels}
    username: ${DB_USERNAME:postgres}
    password: ${DB_USER_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml