spring.application.name: booking.hotels
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: ${DB_HOST:jdbc:postgresql}://${DB_PORT:localhost:5432}/${SCHEMA_NAME:booking_hotels}
    username: ${DB_USERNAME:postgres}
    password: ${DB_USER_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  jwt:
    secret: "my-32-character-ultra-secure-and-ultra-long-secret"
    tokenExpiration: 3m
    refreshTokenExpiration: 30m