spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/booking_hotels
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/booking-hotels-realm
          jwk-set-uri: http://keycloak:8080/realms/booking-hotels-realm/protocol/openid-connect/certs
  cloud:
    stream:
      output-bindings: producer
      bindings:
        producer-out-0:
          destination: statistic
      kafka:
        binder:
          transactionIdPrefix: statistic-
          brokers: kafka:9092
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8070/eureka/
logging:
  level:
    org:
      springframework:
        security: TRACE
server:
  port: 8180